### ISSUE TITLE
[錯誤]: 啟動後指令等無法運作

### ISSUE THREAD

**Issue by Swarmed2674** [Youzi9601/YZBot#26]
### 這是否存在於現有問題？

- [X] 我已經搜索了現有的問題

### 描述問題

無法使用任何指令

### 發生當下

1.輸入指令
2.錯誤

### 版本

```Markdown
- Node:
- npm:
- YZB:
```

### 相關日誌輸出

```Shell
ERROR｜未處理的異步代碼承諾拒絕：
   Promise {
  <rejected> DiscordAPIError[50035]: Invalid Form Body
  embeds[0].color[NUMBER_TYPE_COERCE]: Value "0xFF0000" is not int.
      at SequentialHandler.runRequest (/home/container/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:667:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async SequentialHandler.queueRequest (/home/container/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:464:14)
      at async REST.request (/home/container/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:910:22)
      at async TextChannel.send (/home/container/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15) {
    requestBody: { files: [], json: [Object] },
    rawError: { code: 50035, errors: [Object], message: 'Invalid Form Body' },
    code: 50035,
    status: 400,
    method: 'POST',
    url: 'https://discord.com/api/v10/channels/1066029232595157089/messages'
  }
} 
原因： DiscordAPIError[50035]: Invalid Form Body
embeds[0].color[NUMBER_TYPE_COERCE]: Value "0xFF0000" is not int.
```

### 行為守則

- [X] 我同意遵守該項目的行為準則與確認問題無誤！

**Comment by Youzi9601** [comment]
本人掛了。
DJS 我還沒用好啦...=w=

**Comment by Youzi9601** [comment]
這問題已經修復，單純的顏色代碼的內容寫錯，用成文字而不是數字
